### ISSUE TITLE
Simulation results are automatically deleted after simulation

### ISSUE THREAD

**Issue by sporrasm** [TheSystemDevelopmentKit/spice#26]
Steps to repeat bug:
1. Define spice_iofile object in your testbench
2. After calling spice_iofile constructor in testbench, set self.preserve_iofiles as True
3. Watch your simulation results disappear as quickly as they came

Why this happens:
setting preserve_iofiles as True after constructing the spice_iofile objects does not set the property 'preserve' as True. This apparently happens only if the preserve_iofiles property of spice is set BEFORE instantiating the spice_iofiles. Furthermore, calling the deleter of self.iofile_bundle in spice jumps program execution to the RTL module and not the deleter defined in spice module. The combination of the two creates an effect where spice's preserve_iofiles property has no function. It just deletes everything.

Let's try to fix this at some point

**Comment by ojarvin** [comment]
This is probably fixed by 75c41269dfa2ce8925983b904709ba977884801d

There might be some remaining references to 'preserve' etc. However, now either everything is deleted when preserve_result = False (default) or everything is preserved when it's True. It is safe to use for interactive runs as well, it will just leave the waveform database behind.

@sporrasm If this problem is gone in #28 , you can close this issue as well.
